apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tech-project-depl
  labels:
    app: devops-tech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-tech
  template:
    metadata:
      labels:
        app: devops-tech
    spec:
      containers:
      - name: devops-tech-cont
        image: vangel22/cicd-proj:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata: 
  name: devops-tech-project-srv
spec:
  type: NodePort
  selector:
    app: devops-tech
  ports:
  - name: devops-tech
    port: 3000
    targetPort: 3000
