apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tech-project-depl
  labels:
    app: devops-tech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-tech
  template:
    metadata:
      labels:
        app: devops-tech
    spec:
      containers:
      - name: devops-tech
        image: vangel22/cicd-proj:latest
---
apiVersion: v1
kind: Service
metadata: 
  name: devops-tech-project-srv
spec:
  type: NodePort
  selector:
    app: devops-tech
  ports:
  - name: devops-tech
    port: 3000
    targetPort: 3000
